### ISSUE TITLE
description questions

### ISSUE THREAD

**Issue by adl** [nennigb/amc2moodle#20]
I have several problems written using AMC that I'd like to convert to Moodle.  (And in the future, I'd like to continue writing my problems using AMC before converting them to Moodle, because its much easier than using Moodle's web interface.)

These problems consist in several paragraphs of introduction (and often some pseudo-code and tikz figures), followed by several AMC questions.  All of this is written in one `\element{}{...}` block.

Here is an example:
```
\element{analyse}{

  Some descriptive text presenting the next two functions.

  \begin{multicols}{2}
    \inputminted{c}{exam-201901-fun1.c}
    \columnbreak
    \inputminted{c}{exam-201901-fun2.c}
  \end{multicols}

  \begin{multicols}{2}
\begin{question}{anal1}\bareme{b=1,m=0}
  Question1 text.
 \begin{choices}
  \wrongchoice{...}
  \wrongchoice{...}
  \wrongchoice{...}
  \correctchoice{...}
\end{choices}
\end{question}

\begin{question}{anal2}\bareme{b=2,m=0}
  Question 2 text?
\begin{multicols}{3}
  \begin{choices}[o]
  \wrongchoice{...}
  \wrongchoice{...}
  \correctchoice{...}
  \wrongchoice{...}
  \wrongchoice{...}
  \wrongchoice{...}
\end{choices}
\end{multicols}
\end{question}

More description.

\begin{question}{anal3}\bareme{b=1,m=0}
  Question3 text.
 \begin{choices}
  \wrongchoice{...}
  \correctchoice{...}
\end{choices}
\end{question}

  \end{multicols}
}

```

Currently `amc2moodle` will only convert the questions, but those questions alone are meaningless without the introductory text.   Note that we can also have some text between questions, as between question 2 and 3 above (although I could live without).

One plan would be to extract the text that is part of `\element{}` but not part of any question to create `type="description"` questions.  The `\element{}` macro gives the category of the question but we need to name the descriptions somehow.  And to ease the creation of the moodle quiz, it would best if the various moodle questions (so this includes the descriptions) have name that are alphabetically ordered.

What would you think about the following plan: if `amc2moodle` detects that `\element` contains description text, then all questions names would be prefixed by some number representing the index of this question.  In addition to help the author ordering the question on moodle, the number prefix would make each question name unique, allowing all descriptive questions to be named simply `description`.  For the above example, the names would be:

```
1.description
2.anal1
3.anal2
4.description
5.anal3
```

For extracting the description questions, I'm thinking that maybe one option is to open some tag in `\element{}`, then close it upon entering `\begin{question}` and reopen it when exiting the question.  Then we need some way to remove those tags if they are empty.

What do you think?

PS: the above example also raises another issue, which isn't very important to me at this point: removing `multicols` seems OK when it's used to arrange questions or answers, but it could also be legitimately used in the text of a question.

**Comment by nennigb** [comment]
Hi,

In moodle `description question` are intended to provide such common information. I didn't know this fonctionality of the `element` environment. Personally I was using the `\exemplaire` (`\onecopy`) environment to realize similar thing.

For the moment, in the conversion, `element` is map to moodle category and mimic its behavior. It is possible to do what your suggest, but I am afraid that we will loose some robustness, since the description can be almost everything without any proper container...

Another approach is to use a `question` environment. It will be more close to the moodle workflow, and will add safety since the description content will be encapsulated and well delimited.
AMC has `\indicativeQuestion` (short cut to change the scoring) that is also close to this idea. I have made some tries and AMC doesn't expect that `\choices` are present. Thus it could work for moodle and AMC.
The cons are : it is written 'Question' in AMC but It should possible to change that; problem for ref/label in latex but such cross references will also break in moodle

Another possibility is to add a new environment, and perhaps an amc2moodle sty file...

A last possibility could be to make a PR to AMC to add optional parameters to the question environment. This option could be ignored by AMC and use by amc2moodle....

Benoit

ps I have noted  your queries for multicols, but I think it is not priority.

**Comment by nennigb** [comment]
Using the content of `element` will be difficult since :
There is no semantic to limit what should be put in the description. The content is defined as not the `question`, but this approach will fails if you have something like
```
\element{problem}{
  description 1
  question a
  description 2
  question b
}
```
where the 'description 1' and 'description 2' and will be merged. 

In my opinion, to keep things simple and close to moodle workflow, I will implement the following rule (excepted if somebody propose something else ;-) ):
**To create a description question in moodle, one should create a question without answer.**
To work with AMC `\QuestionIndicative` should be added :
```
\begin{question}{Description} \QuestionIndicative
Just a short description of a problem, provide useful notation, pictures, equations... but not a question.
\end{question}
```

Are you agree with this approach ?

**Comment by nennigb** [comment]
Finally, I have implemented this approach. We can do better in the future by adding new command in AMC latex format, to change `question` into `description` or to add sementic in  `element` environnement.
